print ("Rb Denzel H. Mistal") 
print ("Brgy.Janagdong, Mogpog, Marinduque") 
print ("May 7, 2003")
print ("BSI/T")
print ("2")
print ("C")
print ("Kpop Merch Collecting")
print ("Drawing")
print ("Editing")
print ("Playing Video Games")
print ("Jogging")
